<?php

namespace App\Models;

use Haruncpi\LaravelIdGenerator\IdGenerator;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Model $model) {
            if (is_null($model->code)) {
                $code = IdGenerator::generate([
                    'table' => 'customers',
                    'field' => 'code',
                    'length' => 11,
                    'prefix' => 'CUST-']);
                $model->setAttribute('code',$code);
            }
        });

    }
}
