<?php

namespace App\Models;

use Haruncpi\LaravelIdGenerator\IdGenerator;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Model $model) {
            if (is_null($model->getAttribute('code'))) {
                $documentno = IdGenerator::generate([
                    'table' => 'invoices',
                    'field' => 'documentno',
                    'length' => 10,
                    'prefix' => 'INV-']);
                $model->setAttribute('documentno', $documentno);
            }
        });
    }
}
