<?php

namespace App\Models;

use Haruncpi\LaravelIdGenerator\IdGenerator;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Model $model) {
            if (is_null($model->getAttribute('code'))) {
                $code = IdGenerator::generate([
                    'table' => 'products',
                    'field' => 'code',
                    'length' => 6,
                    'prefix' => 'P-']);
                $model->setAttribute('code', $code);
            }
        });
    }
}
