<?php

namespace App\Models;

use Haruncpi\LaravelIdGenerator\IdGenerator;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductType extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Model $model) {
            if (is_null($model->getAttribute('code'))) {
                $code = IdGenerator::generate([
                    'table' => 'product_types',
                    'field' => 'code',
                    'length' => 10,
                    'prefix' => 'P_TYPE-']);
                $model->setAttribute('code',$code);
            }
        });
    }

    protected $fillable = [
        'code',
        'name'
        ];
}
